import type { Recipe } from "@/types";

export type SeedRecipe = Omit<Recipe, "id" | "ingredients">;

export const SEED_RECIPES: SeedRecipe[] = [
  { nameDe: "Wiener Schnitzel mit Kartoffelsalat", name: "Viennese Schnitzel with Potato Salad", type: "main", category: "meat", meat: "pork", portionGrams: 380, allergens: ["gluten","egg","milk","mustard"], steps: ["Pound veal/pork escalope to 5mm.","Bread classically: flour → egg → breadcrumbs.","Pan-fry in 1cm clarified butter at 170°C until golden, swirl pan.","Serve with warm Bavarian potato salad."], stepsDe: ["Schnitzel auf 5mm klopfen.","Klassisch panieren: Mehl → Ei → Semmelbrösel.","In 1cm Butterschmalz bei 170°C goldgelb backen, Pfanne schwenken.","Mit warmem Kartoffelsalat servieren."], sellPrice: 11.5, basePrice: 4.2, cookTimeMin: 20, kcalPerPortion: 720, source: "internal" },
  { nameDe: "Sauerbraten Rheinisch mit Klößen", name: "Rhenish Sauerbraten with Dumplings", type: "main", category: "meat", meat: "beef", portionGrams: 420, allergens: ["gluten","egg"], steps: ["Marinate beef 4 days in red-wine vinegar with cloves, juniper, bay.","Sear, braise 2.5h with marinade.","Reduce sauce, finish with Lebkuchen and raisins.","Serve with potato dumplings and red cabbage."], stepsDe: ["Rindfleisch 4 Tage in Rotweinessig mit Nelken, Wacholder, Lorbeer marinieren.","Anbraten, 2,5h mit Marinade schmoren.","Soße reduzieren, mit Lebkuchen und Rosinen abrunden.","Mit Kartoffelklößen und Rotkohl servieren."], sellPrice: 13.9, basePrice: 5.6, cookTimeMin: 180, kcalPerPortion: 780, source: "internal" },
  { nameDe: "Königsberger Klopse", name: "Königsberg Meatballs in Caper Sauce", type: "main", category: "meat", meat: "beef", portionGrams: 380, allergens: ["gluten","egg","milk","fish"], steps: ["Mix beef/pork mince with soaked roll, onion, anchovy, egg.","Form klopse, simmer 15min in stock.","Roux with butter/flour, mount with stock + cream.","Finish sauce with capers and lemon."], stepsDe: ["Hack mit eingeweichter Semmel, Zwiebel, Sardelle, Ei mischen.","Klopse formen, 15min in Brühe ziehen.","Mehlschwitze ansetzen, mit Brühe + Sahne aufgießen.","Soße mit Kapern und Zitrone abschmecken."], sellPrice: 10.9, basePrice: 3.8, cookTimeMin: 45, kcalPerPortion: 640, source: "internal" },
  { nameDe: "Rinderrouladen mit Rotkohl", name: "Beef Roulades with Red Cabbage", type: "main", category: "meat", meat: "beef", portionGrams: 420, allergens: ["mustard","gluten"], steps: ["Top beef slices with mustard, bacon, onion, gherkin.","Roll, fix with twine, brown all sides.","Braise 90min in red wine + stock.","Bind sauce, serve with red cabbage + dumplings."], stepsDe: ["Rinderscheiben mit Senf, Speck, Zwiebel, Gewürzgurke belegen.","Aufrollen, binden, rundum anbraten.","90min in Rotwein + Brühe schmoren.","Soße binden, mit Rotkohl + Klößen servieren."], sellPrice: 13.5, basePrice: 5.2, cookTimeMin: 120, kcalPerPortion: 760, source: "internal" },
  { nameDe: "Schweinebraten mit Knödel", name: "Pork Roast with Bread Dumplings", type: "main", category: "meat", meat: "pork", portionGrams: 430, allergens: ["gluten","egg","milk"], steps: ["Score pork shoulder skin in diamonds.","Roast 90min at 180°C with caraway, beer in pan.","Crank to 220°C 15min for crackling.","Slice, serve with bread dumplings and dark gravy."], stepsDe: ["Schweinekrustenbraten Schwarte rautenförmig einschneiden.","90min bei 180°C mit Kümmel, Bier in der Form garen.","Letzte 15min auf 220°C für Kruste.","Schneiden, mit Semmelknödeln und dunkler Soße servieren."], sellPrice: 12.5, basePrice: 4.6, cookTimeMin: 110, kcalPerPortion: 820, source: "internal" },
  { nameDe: "Currywurst mit Pommes", name: "Curry Sausage with Fries", type: "main", category: "meat", meat: "pork", portionGrams: 380, allergens: ["gluten","mustard"], steps: ["Pan-fry bratwurst, slice.","Make sauce: tomato passata + sugar + paprika + curry powder.","Toss sausage in sauce, dust with curry.","Serve with fries and mayo."], stepsDe: ["Bratwurst braten, in Scheiben schneiden.","Soße: Tomatensugo + Zucker + Paprika + Currypulver.","Wurst in Soße schwenken, mit Curry bestreuen.","Mit Pommes und Mayo servieren."], sellPrice: 8.5, basePrice: 2.4, cookTimeMin: 20, kcalPerPortion: 880, source: "internal" },
  { nameDe: "Frikadellen mit Kartoffelpüree", name: "German Meatballs with Mashed Potato", type: "main", category: "meat", meat: "beef", portionGrams: 400, allergens: ["gluten","egg","milk"], steps: ["Mix mince with soaked roll, egg, onion, mustard, marjoram.","Form patties, pan-fry 4min per side.","Cook potatoes, mash with hot milk + butter.","Serve with brown gravy."], stepsDe: ["Hack mit Brötchen, Ei, Zwiebel, Senf, Majoran mischen.","Bouletten formen, je Seite 4min braten.","Kartoffeln kochen, mit heißer Milch + Butter stampfen.","Mit brauner Soße servieren."], sellPrice: 9.5, basePrice: 3.0, cookTimeMin: 35, kcalPerPortion: 690, source: "internal" },
  { nameDe: "Gulasch mit Spätzle", name: "Goulash with Spätzle", type: "main", category: "meat", meat: "beef", portionGrams: 420, allergens: ["gluten","egg","celery"], steps: ["Sweat lots of onions golden, add paprika.","Brown beef cubes, deglaze with stock.","Simmer 90min until tender.","Press fresh Spätzle, serve."], stepsDe: ["Viele Zwiebeln goldgelb dünsten, Paprika hinzu.","Rindswürfel anbraten, mit Brühe ablöschen.","90min weichschmoren.","Frische Spätzle pressen, dazu reichen."], sellPrice: 11.5, basePrice: 4.4, cookTimeMin: 110, kcalPerPortion: 720, source: "internal" },
  { nameDe: "Hähnchenschnitzel mit Reis", name: "Chicken Schnitzel with Rice", type: "main", category: "meat", meat: "chicken", portionGrams: 380, allergens: ["gluten","egg"], steps: ["Bread chicken breast classically.","Fry in butter+oil 3min per side.","Steam basmati rice.","Serve with lemon wedge."], stepsDe: ["Hähnchenbrust panieren.","In Butter+Öl je Seite 3min braten.","Basmatireis dämpfen.","Mit Zitronenspalte servieren."], sellPrice: 9.9, basePrice: 3.2, cookTimeMin: 25, kcalPerPortion: 620, source: "internal" },
  { nameDe: "Kasseler mit Sauerkraut", name: "Smoked Pork Loin with Sauerkraut", type: "main", category: "meat", meat: "pork", portionGrams: 420, allergens: [], steps: ["Slice Kasseler, warm in covered pan.","Heat sauerkraut with onion, juniper, apple, white wine.","Boil potatoes.","Plate with mustard."], stepsDe: ["Kasseler in Scheiben schneiden, im geschlossenen Topf erwärmen.","Sauerkraut mit Zwiebel, Wacholder, Apfel, Weißwein erhitzen.","Salzkartoffeln kochen.","Mit Senf anrichten."], sellPrice: 10.9, basePrice: 4.0, cookTimeMin: 40, kcalPerPortion: 700, source: "internal" },

  { nameDe: "Käsespätzle mit Röstzwiebeln", name: "Cheese Spätzle with Crispy Onions", type: "main", category: "vegetarian", meat: "none", portionGrams: 380, allergens: ["gluten","egg","milk"], steps: ["Make Spätzle dough (flour, egg, water, salt), press into boiling water.","Layer with grated Bergkäse + Emmentaler.","Bake 8min at 200°C.","Top with crispy onions."], stepsDe: ["Spätzleteig (Mehl, Ei, Wasser, Salz), in Salzwasser pressen.","Mit Bergkäse + Emmentaler schichten.","8min bei 200°C überbacken.","Mit Röstzwiebeln bestreuen."], sellPrice: 9.9, basePrice: 2.6, cookTimeMin: 35, kcalPerPortion: 760, source: "internal" },
  { nameDe: "Maultaschen in Brühe", name: "Maultaschen in Broth", type: "main", category: "vegetarian", meat: "none", portionGrams: 380, allergens: ["gluten","egg","milk","celery"], steps: ["Fill pasta sheets with spinach, ricotta, breadcrumbs, herbs.","Cut, simmer 6min in vegetable broth.","Serve in bowl with broth + chives."], stepsDe: ["Nudelteig mit Spinat, Ricotta, Bröseln, Kräutern füllen.","Schneiden, 6min in Gemüsebrühe ziehen.","In Schale mit Brühe + Schnittlauch servieren."], sellPrice: 10.5, basePrice: 3.0, cookTimeMin: 45, kcalPerPortion: 540, source: "internal" },
  { nameDe: "Bauernfrühstück", name: "Farmer's Breakfast", type: "main", category: "vegetarian", meat: "none", portionGrams: 380, allergens: ["egg","milk"], steps: ["Pan-fry diced cooked potatoes with onion + bacon (optional).","Pour over beaten eggs with milk + chives.","Cook until set, slide onto plate."], stepsDe: ["Gewürfelte Pellkartoffeln mit Zwiebel + Speck (optional) braten.","Verquirlte Eier mit Milch + Schnittlauch darüber gießen.","Stocken lassen, auf Teller gleiten."], sellPrice: 8.9, basePrice: 2.0, cookTimeMin: 25, kcalPerPortion: 580, source: "internal" },
  { nameDe: "Kartoffelpuffer mit Apfelmus", name: "Potato Pancakes with Apple Sauce", type: "main", category: "vegetarian", meat: "none", portionGrams: 320, allergens: ["egg","gluten"], steps: ["Grate raw potatoes + onion, squeeze dry.","Bind with egg, flour, salt, nutmeg.","Pan-fry crispy in oil.","Serve with cold apple sauce."], stepsDe: ["Rohe Kartoffeln + Zwiebel reiben, ausdrücken.","Mit Ei, Mehl, Salz, Muskat binden.","In Öl knusprig braten.","Mit kaltem Apfelmus servieren."], sellPrice: 7.9, basePrice: 1.8, cookTimeMin: 30, kcalPerPortion: 520, source: "internal" },
  { nameDe: "Spinat-Lasagne", name: "Spinach Lasagna", type: "main", category: "vegetarian", meat: "none", portionGrams: 400, allergens: ["gluten","egg","milk"], steps: ["Wilt spinach with garlic + nutmeg.","Make béchamel.","Layer pasta, spinach, ricotta, béchamel, parmesan.","Bake 35min at 180°C."], stepsDe: ["Spinat mit Knoblauch + Muskat schwenken.","Béchamelsoße kochen.","Nudeln, Spinat, Ricotta, Béchamel, Parmesan schichten.","35min bei 180°C backen."], sellPrice: 10.5, basePrice: 2.8, cookTimeMin: 55, kcalPerPortion: 680, source: "internal" },

  { nameDe: "Linsen-Bolognese mit Spaghetti", name: "Lentil Bolognese with Spaghetti", type: "main", category: "vegan", meat: "none", portionGrams: 400, allergens: ["gluten","celery"], steps: ["Sweat soffritto (onion, carrot, celery).","Add red lentils, tomato passata, herbs, stock.","Simmer 20min until creamy.","Toss with al-dente spaghetti."], stepsDe: ["Soffritto (Zwiebel, Karotte, Sellerie) andünsten.","Rote Linsen, Tomaten, Kräuter, Brühe zugeben.","20min cremig köcheln.","Mit bissfesten Spaghetti vermengen."], sellPrice: 8.9, basePrice: 1.8, cookTimeMin: 35, kcalPerPortion: 560, source: "internal" },
  { nameDe: "Gemüse-Curry mit Reis", name: "Vegetable Curry with Rice", type: "main", category: "vegan", meat: "none", portionGrams: 420, allergens: ["soy"], steps: ["Sweat onion + ginger + garlic, add curry paste.","Add coconut milk + seasonal vegetables.","Simmer until tender.","Serve with basmati and lime."], stepsDe: ["Zwiebel + Ingwer + Knoblauch andünsten, Currypaste rösten.","Kokosmilch + Saisongemüse zugeben.","Bissfest köcheln.","Mit Basmati und Limette servieren."], sellPrice: 9.5, basePrice: 2.2, cookTimeMin: 30, kcalPerPortion: 540, source: "internal" },
  { nameDe: "Falafel mit Hummus und Salat", name: "Falafel with Hummus and Salad", type: "main", category: "vegan", meat: "none", portionGrams: 380, allergens: ["sesame","gluten"], steps: ["Blitz soaked chickpeas with herbs, garlic, cumin.","Form balls, deep-fry 4min.","Serve with hummus, tabbouleh, flatbread."], stepsDe: ["Eingeweichte Kichererbsen mit Kräutern, Knoblauch, Kreuzkümmel pürieren.","Bällchen formen, 4min frittieren.","Mit Hummus, Tabouleh, Fladenbrot servieren."], sellPrice: 9.9, basePrice: 2.0, cookTimeMin: 30, kcalPerPortion: 600, source: "internal" },
  { nameDe: "Chili sin Carne", name: "Vegan Chili", type: "main", category: "vegan", meat: "none", portionGrams: 400, allergens: ["soy"], steps: ["Sweat onion + pepper, add soy mince + spices.","Add tomato + kidney beans + corn.","Simmer 25min.","Serve with rice or bread."], stepsDe: ["Zwiebel + Paprika andünsten, Soja-Hack + Gewürze hinzu.","Tomaten + Kidneybohnen + Mais zugeben.","25min köcheln.","Mit Reis oder Brot servieren."], sellPrice: 8.9, basePrice: 2.0, cookTimeMin: 35, kcalPerPortion: 540, source: "internal" },
  { nameDe: "Ofengemüse mit Couscous", name: "Roasted Vegetables with Couscous", type: "main", category: "vegan", meat: "none", portionGrams: 420, allergens: ["gluten"], steps: ["Toss zucchini, pepper, eggplant, onion in oil + za'atar.","Roast 25min at 220°C.","Pour boiling stock over couscous.","Plate with lemon."], stepsDe: ["Zucchini, Paprika, Aubergine, Zwiebel in Öl + Za'atar wenden.","25min bei 220°C rösten.","Couscous mit kochender Brühe übergießen.","Mit Zitrone anrichten."], sellPrice: 8.5, basePrice: 1.6, cookTimeMin: 35, kcalPerPortion: 480, source: "internal" },

  { nameDe: "Forellenfilet mit Mandelbutter", name: "Trout Fillet with Almond Butter", type: "main", category: "fish", meat: "none", portionGrams: 360, allergens: ["fish","milk","nuts"], steps: ["Pan-fry trout fillets skin-side first 3min.","Flip 2min.","Brown butter with sliced almonds + lemon.","Serve with parsley potatoes."], stepsDe: ["Forellenfilets zuerst 3min auf der Haut braten.","Wenden, 2min.","Butter mit Mandelblättchen + Zitrone bräunen.","Mit Petersilienkartoffeln servieren."], sellPrice: 13.5, basePrice: 5.0, cookTimeMin: 25, kcalPerPortion: 580, source: "internal" },
  { nameDe: "Backfisch mit Remoulade", name: "Battered Fish with Remoulade", type: "main", category: "fish", meat: "none", portionGrams: 380, allergens: ["fish","gluten","egg","mustard"], steps: ["Beer batter: flour + cold beer + salt.","Coat pollock fillets, deep-fry 5min at 175°C.","Serve with remoulade, lemon, fries."], stepsDe: ["Bierteig: Mehl + kaltes Bier + Salz.","Seelachs darin wenden, 5min bei 175°C frittieren.","Mit Remoulade, Zitrone, Pommes servieren."], sellPrice: 11.5, basePrice: 3.8, cookTimeMin: 25, kcalPerPortion: 720, source: "internal" },

  { nameDe: "Linsensuppe mit Wiener", name: "Lentil Soup with Sausage", type: "soup", category: "meat", meat: "pork", portionGrams: 350, allergens: ["celery","gluten"], steps: ["Sweat soffritto, add brown lentils + stock + bay.","Simmer 35min until tender.","Splash of vinegar, slice in Wiener.","Heat through, season."], stepsDe: ["Soffritto andünsten, braune Linsen + Brühe + Lorbeer zugeben.","35min weich köcheln.","Schuss Essig, Wiener in Scheiben.","Erhitzen, abschmecken."], sellPrice: 6.9, basePrice: 1.8, cookTimeMin: 50, kcalPerPortion: 420, source: "internal" },
  { nameDe: "Erbsensuppe", name: "Pea Soup", type: "soup", category: "meat", meat: "pork", portionGrams: 350, allergens: ["celery"], steps: ["Sweat soffritto + diced bacon.","Add yellow split peas + stock.","Simmer 45min, blend half.","Add diced bockwurst, season with marjoram."], stepsDe: ["Soffritto + Speckwürfel andünsten.","Gelbe Schälerbsen + Brühe zugeben.","45min köcheln, Hälfte pürieren.","Bockwurstwürfel zugeben, mit Majoran abschmecken."], sellPrice: 6.5, basePrice: 1.6, cookTimeMin: 60, kcalPerPortion: 420, source: "internal" },
  { nameDe: "Tomatensuppe mit Basilikum", name: "Tomato Soup with Basil", type: "soup", category: "vegetarian", meat: "none", portionGrams: 320, allergens: ["milk","celery"], steps: ["Sweat onion + garlic, add tomato passata + stock + sugar pinch.","Simmer 20min, blend smooth.","Finish with cream + torn basil."], stepsDe: ["Zwiebel + Knoblauch andünsten, Tomatensugo + Brühe + Prise Zucker zugeben.","20min köcheln, fein pürieren.","Mit Sahne + Basilikum abrunden."], sellPrice: 5.5, basePrice: 1.2, cookTimeMin: 30, kcalPerPortion: 280, source: "internal" },
  { nameDe: "Kürbissuppe Hokkaido", name: "Hokkaido Pumpkin Soup", type: "soup", category: "vegan", meat: "none", portionGrams: 320, allergens: [], steps: ["Roast pumpkin chunks with ginger + chili.","Combine with sweated onion, stock, coconut milk.","Blend smooth, top with pumpkin oil + seeds."], stepsDe: ["Hokkaido-Stücke mit Ingwer + Chili rösten.","Mit gedünsteter Zwiebel, Brühe, Kokosmilch verbinden.","Fein pürieren, mit Kürbiskernöl + Kernen toppen."], sellPrice: 5.9, basePrice: 1.2, cookTimeMin: 35, kcalPerPortion: 260, source: "internal" },
  { nameDe: "Gulaschsuppe", name: "Goulash Soup", type: "soup", category: "meat", meat: "beef", portionGrams: 380, allergens: ["celery","gluten"], steps: ["Sweat onions golden, paprika, beef cubes.","Deglaze with stock + tomato + diced potato + pepper.","Simmer 75min."], stepsDe: ["Zwiebeln goldgelb dünsten, Paprika, Rindswürfel.","Mit Brühe + Tomate + Kartoffelwürfeln + Paprika ablöschen.","75min köcheln."], sellPrice: 7.5, basePrice: 2.4, cookTimeMin: 90, kcalPerPortion: 460, source: "internal" },

  { nameDe: "Bunter Salat mit Hähnchenstreifen", name: "Mixed Salad with Chicken Strips", type: "salad", category: "meat", meat: "chicken", portionGrams: 320, allergens: ["mustard","sesame"], steps: ["Pan-fry seasoned chicken strips.","Toss leaves with cucumber, tomato, pepper, croutons.","Honey-mustard vinaigrette."], stepsDe: ["Hähnchenstreifen würzig braten.","Salat mit Gurke, Tomate, Paprika, Croutons mischen.","Honig-Senf-Vinaigrette."], sellPrice: 9.9, basePrice: 2.6, cookTimeMin: 20, kcalPerPortion: 420, source: "internal" },
  { nameDe: "Krautsalat", name: "Cabbage Slaw", type: "salad", category: "vegan", meat: "none", portionGrams: 200, allergens: ["mustard"], steps: ["Shred white cabbage finely, salt, knead 10min.","Dress with caraway, vinegar, oil, sugar pinch."], stepsDe: ["Weißkohl fein hobeln, salzen, 10min kneten.","Mit Kümmel, Essig, Öl, Prise Zucker abschmecken."], sellPrice: 3.5, basePrice: 0.6, cookTimeMin: 15, kcalPerPortion: 180, source: "internal" },

  { nameDe: "Apfelstrudel mit Vanillesoße", name: "Apple Strudel with Vanilla Sauce", type: "dessert", category: "vegetarian", meat: "none", portionGrams: 220, allergens: ["gluten","egg","milk","nuts"], steps: ["Stretch strudel dough thinly, brush with butter.","Fill with apple, raisins, cinnamon, breadcrumbs, walnuts.","Roll, bake 30min at 190°C.","Serve warm with vanilla sauce."], stepsDe: ["Strudelteig dünn ausziehen, mit Butter bestreichen.","Mit Apfel, Rosinen, Zimt, Bröseln, Walnüssen füllen.","Rollen, 30min bei 190°C backen.","Warm mit Vanillesoße servieren."], sellPrice: 5.9, basePrice: 1.4, cookTimeMin: 60, kcalPerPortion: 460, source: "internal" },
  { nameDe: "Kaiserschmarrn mit Zwetschgenröster", name: "Kaiserschmarrn with Plum Compote", type: "dessert", category: "vegetarian", meat: "none", portionGrams: 280, allergens: ["gluten","egg","milk"], steps: ["Whip egg whites, fold into milk-flour-yolk batter with raisins.","Cook in butter, tear with two forks, dust with sugar.","Serve with warm plum compote."], stepsDe: ["Eiweiß steif schlagen, in Milch-Mehl-Eigelb-Teig mit Rosinen unterheben.","In Butter ausbacken, mit zwei Gabeln zerreißen, mit Zucker stauben.","Mit warmem Zwetschgenröster servieren."], sellPrice: 6.5, basePrice: 1.6, cookTimeMin: 30, kcalPerPortion: 540, source: "internal" },
  { nameDe: "Milchreis mit Zimt-Zucker", name: "Rice Pudding with Cinnamon Sugar", type: "dessert", category: "vegetarian", meat: "none", portionGrams: 280, allergens: ["milk"], steps: ["Simmer pudding rice in milk + sugar + vanilla 35min, stirring.","Serve hot or cold with cinnamon sugar and stewed fruit."], stepsDe: ["Milchreis 35min unter Rühren in Milch + Zucker + Vanille köcheln.","Heiß oder kalt mit Zimtzucker und Kompott servieren."], sellPrice: 4.5, basePrice: 1.0, cookTimeMin: 40, kcalPerPortion: 380, source: "internal" },
];
