/**
 * Seed the recipe_library table with classic German / Austrian canteen recipes.
 *
 * Idempotent: upserts by (name_de). Re-running is safe.
 *
 * Usage:
 *   pnpm --filter @workspace/scripts run seed:recipes
 *
 * Env requirements:
 *   - DATABASE_URL
 */

import { db, recipeLibrary } from "@workspace/db";
import { sql } from "drizzle-orm";
import { randomUUID } from "crypto";

// ── Recipe data ───────────────────────────────────────────────────────────────

type RecipeSeed = Omit<typeof recipeLibrary.$inferInsert, "id" | "createdAt">;

const RECIPES: RecipeSeed[] = [
  // ── Suppen ──────────────────────────────────────────────────────────────────
  {
    nameDe: "Kartoffelsuppe",
    name: "Potato Soup",
    type: "soup", category: "vegan", meat: "none",
    portionGrams: 350, basePrice: 0.90, sellPrice: 3.20, cookTimeMin: 35,
    kcalPerPortion: 220, protein: 5, fat: 6, carbs: 36,
    allergens: [],
    tags: ["klassiker", "herbst", "winter", "günstig"],
    stepsDe: [
      "Kartoffeln schälen und würfeln. Zwiebel und Lauch fein schneiden.",
      "Öl im Topf erhitzen, Zwiebel und Lauch glasig anschwitzen.",
      "Kartoffeln zugeben, mit Gemüsebrühe auffüllen und 20 Minuten köcheln.",
      "Suppe pürieren, mit Salz, Pfeffer und Muskat abschmecken.",
      "Mit Schnittlauch garnieren und servieren.",
    ],
    steps: [
      "Peel and dice potatoes. Finely chop onion and leek.",
      "Heat oil in pot, sweat onion and leek until translucent.",
      "Add potatoes, cover with vegetable stock and simmer 20 minutes.",
      "Blend soup, season with salt, pepper and nutmeg.",
      "Garnish with chives and serve.",
    ],
  },
  {
    nameDe: "Linsensuppe",
    name: "Lentil Soup",
    type: "soup", category: "vegan", meat: "none",
    portionGrams: 350, basePrice: 0.80, sellPrice: 3.00, cookTimeMin: 40,
    kcalPerPortion: 260, protein: 14, fat: 4, carbs: 40,
    allergens: [],
    tags: ["klassiker", "winter", "protein", "günstig"],
    stepsDe: [
      "Rote Linsen waschen. Zwiebel und Knoblauch würfeln.",
      "Zwiebel in Öl anbraten, Knoblauch und Kreuzkümmel kurz mitrösten.",
      "Linsen und Gemüsebrühe zugeben, 25 Minuten köcheln.",
      "Mit Zitronensaft, Salz und Pfeffer abschmecken.",
      "Mit Paprikapulver bestreuen und servieren.",
    ],
    steps: [
      "Rinse red lentils. Dice onion and garlic.",
      "Fry onion in oil, briefly toast garlic and cumin.",
      "Add lentils and vegetable stock, simmer 25 minutes.",
      "Season with lemon juice, salt and pepper.",
      "Sprinkle with paprika and serve.",
    ],
  },
  {
    nameDe: "Tomatensuppe",
    name: "Tomato Soup",
    type: "soup", category: "vegan", meat: "none",
    portionGrams: 350, basePrice: 0.70, sellPrice: 2.80, cookTimeMin: 25,
    kcalPerPortion: 140, protein: 4, fat: 3, carbs: 24,
    allergens: [],
    tags: ["klassiker", "schnell", "leicht"],
    stepsDe: [
      "Zwiebel und Knoblauch anschwitzen. Tomatenmark kurz mitrösten.",
      "Passata und Gemüsebrühe zugeben, 15 Minuten köcheln.",
      "Mit Salz, Pfeffer, Zucker und Basilikum abschmecken.",
      "Suppe pürieren und mit Sahne verfeinern.",
    ],
    steps: [
      "Sweat onion and garlic. Briefly fry tomato paste.",
      "Add passata and vegetable stock, simmer 15 minutes.",
      "Season with salt, pepper, sugar and basil.",
      "Blend soup and refine with cream.",
    ],
  },
  {
    nameDe: "Erbsensuppe mit Würstchen",
    name: "Pea Soup with Sausage",
    type: "soup", category: "meat", meat: "pork",
    portionGrams: 380, basePrice: 1.40, sellPrice: 4.20, cookTimeMin: 50,
    kcalPerPortion: 380, protein: 22, fat: 12, carbs: 44,
    allergens: ["gluten"],
    tags: ["klassiker", "winter", "satt", "günstig"],
    stepsDe: [
      "Erbsen über Nacht einweichen. Speck würfeln und anbraten.",
      "Zwiebel, Möhren und Sellerie zugeben und anschwitzen.",
      "Erbsen und Brühe zugeben, 40 Minuten köcheln.",
      "Suppe teilweise pürieren, Würstchen in Scheiben schneiden und zugeben.",
      "Mit Majoran, Salz und Pfeffer abschmecken.",
    ],
    steps: [
      "Soak peas overnight. Dice and fry bacon.",
      "Add onion, carrots and celery, sweat briefly.",
      "Add peas and stock, simmer 40 minutes.",
      "Partially blend soup, slice sausages and add.",
      "Season with marjoram, salt and pepper.",
    ],
  },
  {
    nameDe: "Gulaschsuppe",
    name: "Goulash Soup",
    type: "soup", category: "meat", meat: "beef",
    portionGrams: 380, basePrice: 2.00, sellPrice: 5.50, cookTimeMin: 75,
    kcalPerPortion: 340, protein: 24, fat: 14, carbs: 26,
    allergens: ["gluten"],
    tags: ["klassiker", "herbst", "winter", "herzhaft"],
    stepsDe: [
      "Rindfleisch in Würfel schneiden, scharf anbraten und beiseite stellen.",
      "Zwiebeln und Paprika anbraten, Tomatenmark und Paprikapulver einrühren.",
      "Fleisch zurück in den Topf, mit Brühe ablöschen.",
      "60 Minuten bei kleiner Hitze schmoren.",
      "Kartoffeln zugeben und weitere 20 Minuten garen. Abschmecken.",
    ],
    steps: [
      "Cut beef into cubes, sear well and set aside.",
      "Fry onions and peppers, stir in tomato paste and paprika powder.",
      "Return meat to pot, deglaze with stock.",
      "Braise on low heat for 60 minutes.",
      "Add potatoes and cook another 20 minutes. Season.",
    ],
  },
  {
    nameDe: "Hühnerbrühe mit Nudeln",
    name: "Chicken Broth with Noodles",
    type: "soup", category: "meat", meat: "chicken",
    portionGrams: 350, basePrice: 1.10, sellPrice: 3.50, cookTimeMin: 60,
    kcalPerPortion: 180, protein: 16, fat: 5, carbs: 18,
    allergens: ["gluten", "celery"],
    tags: ["klassiker", "leicht", "kinder"],
    stepsDe: [
      "Huhn mit Möhren, Sellerie und Zwiebel in Wasser aufsetzen.",
      "90 Minuten bei niedriger Hitze kochen, dabei abschäumen.",
      "Brühe abseihen, Fleisch zupfen und zurückgeben.",
      "Suppennudeln gar kochen, Gemüse würfeln und zugeben.",
      "Mit Salz und Petersilie abschmecken.",
    ],
    steps: [
      "Place chicken with carrots, celery and onion in water.",
      "Cook on low heat for 90 minutes, skimming foam.",
      "Strain broth, shred meat and return.",
      "Cook soup noodles, dice vegetables and add.",
      "Season with salt and parsley.",
    ],
  },

  // ── Hauptgerichte Fleisch ───────────────────────────────────────────────────
  {
    nameDe: "Wiener Schnitzel",
    name: "Viennese Schnitzel",
    type: "main", category: "meat", meat: "pork",
    portionGrams: 380, basePrice: 3.20, sellPrice: 9.50, cookTimeMin: 25,
    kcalPerPortion: 560, protein: 38, fat: 28, carbs: 38,
    allergens: ["gluten", "egg", "milk"],
    tags: ["klassiker", "österreich", "beliebt"],
    stepsDe: [
      "Schnitzel dünn klopfen, salzen und pfeffern.",
      "Durch Mehl, verquirltes Ei und Semmelbrösel wenden.",
      "In reichlich Butter goldbraun ausbacken (ca. 3 Min. pro Seite).",
      "Auf Küchenkrepp abtropfen lassen.",
      "Mit Zitrone und Petersilienkartoffeln servieren.",
    ],
    steps: [
      "Pound cutlets thin, season with salt and pepper.",
      "Coat in flour, beaten egg and breadcrumbs.",
      "Fry in plenty of butter until golden (approx. 3 min per side).",
      "Drain on kitchen paper.",
      "Serve with lemon and parsley potatoes.",
    ],
  },
  {
    nameDe: "Rindergulasch mit Kartoffelknödeln",
    name: "Beef Goulash with Potato Dumplings",
    type: "main", category: "meat", meat: "beef",
    portionGrams: 450, basePrice: 3.80, sellPrice: 10.50, cookTimeMin: 120,
    kcalPerPortion: 680, protein: 42, fat: 22, carbs: 72,
    allergens: ["gluten", "egg"],
    tags: ["klassiker", "winter", "herzhaft", "satt"],
    stepsDe: [
      "Rindfleisch würfeln, scharf anbraten. Zwiebeln glasig dünsten.",
      "Paprikapulver, Tomatenmark und Brühe zugeben.",
      "2 Stunden schmoren bis das Fleisch zart ist.",
      "Kartoffeln kochen, stampfen, mit Ei und Mehl zu Knödeln formen.",
      "Knödel in Salzwasser 15 Minuten garen. Mit Gulasch servieren.",
    ],
    steps: [
      "Cube beef, sear well. Sauté onions until soft.",
      "Add paprika powder, tomato paste and stock.",
      "Braise 2 hours until meat is tender.",
      "Boil potatoes, mash, shape into dumplings with egg and flour.",
      "Cook dumplings in salted water 15 minutes. Serve with goulash.",
    ],
  },
  {
    nameDe: "Königsberger Klopse",
    name: "Königsberg Meatballs in Caper Sauce",
    type: "main", category: "meat", meat: "beef",
    portionGrams: 420, basePrice: 2.80, sellPrice: 8.50, cookTimeMin: 45,
    kcalPerPortion: 520, protein: 34, fat: 26, carbs: 32,
    allergens: ["gluten", "egg", "milk"],
    tags: ["klassiker", "norddeutsch", "traditionell"],
    stepsDe: [
      "Hackfleisch mit eingeweichtem Brötchen, Ei und Zwiebeln verkneten.",
      "Klopse formen und in Brühe 20 Minuten garen.",
      "Butter-Mehl-Schwitze herstellen, mit Brühe aufgießen.",
      "Kapern, Zitronensaft und Sahne einrühren.",
      "Klopse in der Sauce erhitzen und mit Kartoffeln servieren.",
    ],
    steps: [
      "Knead mince with soaked roll, egg and onions.",
      "Shape meatballs and cook in broth 20 minutes.",
      "Make butter-flour roux, pour in broth.",
      "Stir in capers, lemon juice and cream.",
      "Heat meatballs in sauce and serve with potatoes.",
    ],
  },
  {
    nameDe: "Sauerbraten mit Rotkohl",
    name: "Sauerbraten with Red Cabbage",
    type: "main", category: "meat", meat: "beef",
    portionGrams: 450, basePrice: 4.50, sellPrice: 12.00, cookTimeMin: 180,
    kcalPerPortion: 620, protein: 45, fat: 20, carbs: 55,
    allergens: ["gluten"],
    tags: ["klassiker", "rheinland", "festessen", "traditionell"],
    stepsDe: [
      "Fleisch 2 Tage in Essig-Rotwein-Marinade einlegen.",
      "Fleisch abtupfen, scharf anbraten, Marinade zugeben.",
      "3 Stunden bei 160°C schmoren.",
      "Soße passieren, mit Lebkuchen binden.",
      "Rotkohl mit Äpfeln und Lorbeer schmoren. Zusammen servieren.",
    ],
    steps: [
      "Marinate meat 2 days in vinegar-red wine marinade.",
      "Pat dry, sear well, add marinade.",
      "Braise 3 hours at 160°C.",
      "Strain sauce, thicken with gingerbread.",
      "Braise red cabbage with apples and bay leaf. Serve together.",
    ],
  },
  {
    nameDe: "Hähnchenbrust mit Gemüsereis",
    name: "Chicken Breast with Vegetable Rice",
    type: "main", category: "meat", meat: "chicken",
    portionGrams: 400, basePrice: 2.60, sellPrice: 7.80, cookTimeMin: 30,
    kcalPerPortion: 460, protein: 42, fat: 10, carbs: 48,
    allergens: [],
    tags: ["leicht", "gesund", "alltagsküche"],
    stepsDe: [
      "Hähnchenbrust würzen und in der Pfanne goldbraun anbraten.",
      "Im Ofen bei 180°C 15 Minuten fertig garen.",
      "Reis kochen, Paprika, Erbsen und Mais zugeben.",
      "Mit Gemüsebrühe und Kräutern abschmecken.",
      "Hähnchen aufschneiden und auf dem Reis servieren.",
    ],
    steps: [
      "Season chicken breast and sear golden in pan.",
      "Finish in oven at 180°C for 15 minutes.",
      "Cook rice, add peppers, peas and corn.",
      "Season with vegetable stock and herbs.",
      "Slice chicken and serve on rice.",
    ],
  },
  {
    nameDe: "Bratwurst mit Sauerkraut und Kartoffelpüree",
    name: "Bratwurst with Sauerkraut and Mashed Potato",
    type: "main", category: "meat", meat: "pork",
    portionGrams: 420, basePrice: 2.20, sellPrice: 6.50, cookTimeMin: 25,
    kcalPerPortion: 590, protein: 24, fat: 32, carbs: 48,
    allergens: ["gluten", "milk"],
    tags: ["klassiker", "deutsch", "günstig", "satt"],
    stepsDe: [
      "Bratwürste in der Pfanne rundum anbraten bis goldbraun.",
      "Sauerkraut mit Lorbeer und Kümmel aufwärmen.",
      "Kartoffeln kochen, mit Butter und Milch stampfen.",
      "Mit Salz, Pfeffer und Muskat abschmecken.",
      "Alles zusammen anrichten.",
    ],
    steps: [
      "Fry bratwurst in pan all over until golden.",
      "Heat sauerkraut with bay leaf and caraway.",
      "Boil potatoes, mash with butter and milk.",
      "Season with salt, pepper and nutmeg.",
      "Plate everything together.",
    ],
  },
  {
    nameDe: "Schweinebraten mit Soße und Knödeln",
    name: "Roast Pork with Gravy and Dumplings",
    type: "main", category: "meat", meat: "pork",
    portionGrams: 460, basePrice: 3.00, sellPrice: 9.00, cookTimeMin: 150,
    kcalPerPortion: 700, protein: 48, fat: 30, carbs: 58,
    allergens: ["gluten", "egg"],
    tags: ["klassiker", "bayerisch", "sonntag", "festessen"],
    stepsDe: [
      "Schweineschulter würzen und in der Röhre bei 220°C anbraten.",
      "Temperatur auf 170°C senken, 2 Stunden schmoren.",
      "Bratensatz mit Bier und Brühe ablöschen, Soße kochen.",
      "Semmelknödel aus altem Brot, Milch und Eiern formen.",
      "Knödel 15 Minuten in Salzwasser garen.",
    ],
    steps: [
      "Season pork shoulder and roast at 220°C.",
      "Reduce to 170°C, braise 2 hours.",
      "Deglaze roasting pan with beer and stock, make gravy.",
      "Shape bread dumplings from old bread, milk and eggs.",
      "Cook dumplings 15 minutes in salted water.",
    ],
  },
  {
    nameDe: "Rinderbouletten mit Kartoffeln",
    name: "Beef Patties with Potatoes",
    type: "main", category: "meat", meat: "beef",
    portionGrams: 380, basePrice: 2.20, sellPrice: 6.80, cookTimeMin: 30,
    kcalPerPortion: 520, protein: 32, fat: 24, carbs: 40,
    allergens: ["gluten", "egg"],
    tags: ["klassiker", "kantine", "kinder", "günstig"],
    stepsDe: [
      "Hackfleisch mit Zwiebeln, Ei, Senf und Paniermehl verkneten.",
      "Frikadellen formen und bei mittlerer Hitze beidseitig braten.",
      "Kartoffeln kochen oder als Bratkartoffeln zubereiten.",
      "Mit Senf und Gurkensalat servieren.",
    ],
    steps: [
      "Knead mince with onions, egg, mustard and breadcrumbs.",
      "Shape patties and fry on both sides at medium heat.",
      "Boil potatoes or prepare as fried potatoes.",
      "Serve with mustard and cucumber salad.",
    ],
  },
  {
    nameDe: "Lammkeule mit Rosmarin und Bohnen",
    name: "Leg of Lamb with Rosemary and Beans",
    type: "main", category: "meat", meat: "lamb",
    portionGrams: 400, basePrice: 5.50, sellPrice: 14.00, cookTimeMin: 120,
    kcalPerPortion: 580, protein: 48, fat: 28, carbs: 22,
    allergens: [],
    tags: ["festessen", "ostern", "herbst"],
    stepsDe: [
      "Lammkeule mit Knoblauch spicken, mit Rosmarin und Öl einreiben.",
      "Bei 200°C 20 Minuten anrösten, dann bei 160°C 90 Minuten garen.",
      "Grüne Bohnen in Salzwasser blanchieren.",
      "Bratensatz mit Rotwein ablöschen, Soße reduzieren.",
      "Fleisch ruhen lassen, tranchieren und mit Bohnen servieren.",
    ],
    steps: [
      "Stud lamb with garlic, rub with rosemary and oil.",
      "Roast 20 min at 200°C, then cook at 160°C for 90 min.",
      "Blanch green beans in salted water.",
      "Deglaze with red wine, reduce sauce.",
      "Rest meat, carve and serve with beans.",
    ],
  },
  {
    nameDe: "Putengeschnetzeltes mit Champignons",
    name: "Turkey Strips with Mushrooms",
    type: "main", category: "meat", meat: "turkey",
    portionGrams: 380, basePrice: 2.80, sellPrice: 8.20, cookTimeMin: 25,
    kcalPerPortion: 420, protein: 40, fat: 16, carbs: 22,
    allergens: ["milk", "gluten"],
    tags: ["leicht", "alltagsküche", "kantine"],
    stepsDe: [
      "Putenbruststreifen scharf anbraten, beiseite stellen.",
      "Champignons in Butter anbraten, Zwiebeln zugeben.",
      "Mit Weißwein ablöschen, Sahne zugeben.",
      "Fleisch zurück in die Sauce, 5 Minuten ziehen lassen.",
      "Mit Salz, Pfeffer und Petersilie abschmecken. Mit Nudeln servieren.",
    ],
    steps: [
      "Sear turkey strips well, set aside.",
      "Fry mushrooms in butter, add onions.",
      "Deglaze with white wine, add cream.",
      "Return meat to sauce, let steep 5 minutes.",
      "Season with salt, pepper and parsley. Serve with pasta.",
    ],
  },

  // ── Hauptgerichte Fisch ─────────────────────────────────────────────────────
  {
    nameDe: "Lachsfilet mit Dillsauce",
    name: "Salmon Fillet with Dill Sauce",
    type: "main", category: "fish", meat: "none",
    portionGrams: 360, basePrice: 4.80, sellPrice: 12.50, cookTimeMin: 20,
    kcalPerPortion: 460, protein: 38, fat: 26, carbs: 12,
    allergens: ["fish", "milk"],
    tags: ["gesund", "leicht", "omega3"],
    stepsDe: [
      "Lachsfilet salzen und pfeffern.",
      "In Butter von beiden Seiten je 3 Minuten braten.",
      "Crème fraîche mit frischem Dill und Zitronensaft verrühren.",
      "Sauce erwärmen, nicht kochen.",
      "Lachs mit Dillsauce und Salzkartoffeln servieren.",
    ],
    steps: [
      "Season salmon fillet with salt and pepper.",
      "Fry in butter 3 minutes each side.",
      "Mix crème fraîche with fresh dill and lemon juice.",
      "Warm sauce, do not boil.",
      "Serve salmon with dill sauce and boiled potatoes.",
    ],
  },
  {
    nameDe: "Seelachs mit Senf-Sahne-Sauce",
    name: "Pollock with Mustard Cream Sauce",
    type: "main", category: "fish", meat: "none",
    portionGrams: 360, basePrice: 2.80, sellPrice: 7.50, cookTimeMin: 20,
    kcalPerPortion: 380, protein: 34, fat: 18, carbs: 16,
    allergens: ["fish", "milk", "mustard"],
    tags: ["kantine", "günstig", "freitag"],
    stepsDe: [
      "Fischfilet salzen und in Öl anbraten.",
      "Sahne mit Senf und Brühe aufkochen.",
      "Sauce mit Salz und Pfeffer abschmecken.",
      "Fisch in die Sauce legen und 5 Minuten ziehen lassen.",
      "Mit Reis und Gemüse servieren.",
    ],
    steps: [
      "Season fish fillet and fry in oil.",
      "Bring cream, mustard and stock to a boil.",
      "Season sauce with salt and pepper.",
      "Place fish in sauce and steep 5 minutes.",
      "Serve with rice and vegetables.",
    ],
  },
  {
    nameDe: "Backhendl mit Kartoffelsalat",
    name: "Fried Chicken with Potato Salad",
    type: "main", category: "meat", meat: "chicken",
    portionGrams: 420, basePrice: 2.80, sellPrice: 8.50, cookTimeMin: 35,
    kcalPerPortion: 620, protein: 36, fat: 30, carbs: 46,
    allergens: ["gluten", "egg", "milk"],
    tags: ["österreich", "klassiker", "beliebt", "kinder"],
    stepsDe: [
      "Hähnchenteile würzen, in Mehl, Ei und Bröseln panieren.",
      "In Butterschmalz goldbraun ausbacken.",
      "Kartoffeln kochen, abkühlen und in Scheiben schneiden.",
      "Marinade aus Essig, Öl, Senf und Brühe anrühren.",
      "Kartoffeln marinieren, 30 Minuten ziehen lassen.",
    ],
    steps: [
      "Season chicken pieces, coat in flour, egg and breadcrumbs.",
      "Fry golden in clarified butter.",
      "Boil potatoes, cool and slice.",
      "Mix marinade of vinegar, oil, mustard and stock.",
      "Marinate potatoes, let sit 30 minutes.",
    ],
  },

  // ── Vegetarisch / Vegan ─────────────────────────────────────────────────────
  {
    nameDe: "Käsespätzle",
    name: "Cheese Spaetzle",
    type: "main", category: "vegetarian", meat: "none",
    portionGrams: 380, basePrice: 1.60, sellPrice: 5.80, cookTimeMin: 30,
    kcalPerPortion: 620, protein: 24, fat: 28, carbs: 66,
    allergens: ["gluten", "egg", "milk"],
    tags: ["klassiker", "allgäu", "käse", "vegetarisch"],
    stepsDe: [
      "Spätzleteig aus Mehl, Eiern, Salz und Wasser rühren.",
      "Teig durch Spätzlesieb in kochendes Salzwasser streichen.",
      "Spätzle schichtweise mit geriebenem Emmentaler in Auflaufform schichten.",
      "Mit Röstzwiebeln toppen.",
      "Im Ofen bei 180°C überbacken bis der Käse schmilzt.",
    ],
    steps: [
      "Mix spaetzle batter from flour, eggs, salt and water.",
      "Press batter through spaetzle press into boiling salted water.",
      "Layer spaetzle with grated Emmental in baking dish.",
      "Top with fried onions.",
      "Bake at 180°C until cheese melts.",
    ],
  },
  {
    nameDe: "Gemüsecurry mit Basmatireis",
    name: "Vegetable Curry with Basmati Rice",
    type: "main", category: "vegan", meat: "none",
    portionGrams: 400, basePrice: 1.40, sellPrice: 5.20, cookTimeMin: 30,
    kcalPerPortion: 380, protein: 10, fat: 8, carbs: 66,
    allergens: [],
    tags: ["vegan", "gesund", "international", "farbenfroh"],
    stepsDe: [
      "Zwiebeln und Knoblauch anschwitzen, Currypulver und Ingwer zugeben.",
      "Paprika, Zucchini und Kichererbsen zugeben.",
      "Kokosmilch einrühren und 15 Minuten köcheln.",
      "Mit Salz, Limette und Koriander abschmecken.",
      "Mit gekochtem Basmatireis servieren.",
    ],
    steps: [
      "Sweat onions and garlic, add curry powder and ginger.",
      "Add peppers, courgette and chickpeas.",
      "Stir in coconut milk and simmer 15 minutes.",
      "Season with salt, lime and coriander.",
      "Serve with cooked basmati rice.",
    ],
  },
  {
    nameDe: "Spinat-Ricotta-Knödel mit Salbeibutter",
    name: "Spinach Ricotta Dumplings with Sage Butter",
    type: "main", category: "vegetarian", meat: "none",
    portionGrams: 360, basePrice: 1.80, sellPrice: 6.50, cookTimeMin: 35,
    kcalPerPortion: 480, protein: 20, fat: 26, carbs: 40,
    allergens: ["gluten", "egg", "milk"],
    tags: ["vegetarisch", "italien", "käse"],
    stepsDe: [
      "Spinat blanchieren, ausdrücken und hacken.",
      "Mit Ricotta, Parmesan, Ei und Mehl zu einer Masse vermengen.",
      "Zu Knödeln formen und in Salzwasser 8 Minuten garen.",
      "Butter in Pfanne erhitzen, Salbeiblätter knusprig braten.",
      "Knödel in Salbeibutter schwenken und mit Parmesan servieren.",
    ],
    steps: [
      "Blanch spinach, squeeze out and chop.",
      "Mix with ricotta, Parmesan, egg and flour.",
      "Shape into dumplings and cook in salted water 8 minutes.",
      "Heat butter in pan, fry sage leaves until crispy.",
      "Toss dumplings in sage butter and serve with Parmesan.",
    ],
  },
  {
    nameDe: "Gemüseauflauf",
    name: "Vegetable Gratin",
    type: "main", category: "vegetarian", meat: "none",
    portionGrams: 380, basePrice: 1.50, sellPrice: 5.50, cookTimeMin: 50,
    kcalPerPortion: 340, protein: 14, fat: 16, carbs: 34,
    allergens: ["milk", "egg"],
    tags: ["vegetarisch", "beilage", "überbacken"],
    stepsDe: [
      "Zucchini, Paprika und Tomaten in Scheiben schneiden.",
      "In einer Auflaufform schichten und würzen.",
      "Sahne-Eier-Mischung darübergießen.",
      "Mit Käse bestreuen und bei 180°C 35 Minuten backen.",
    ],
    steps: [
      "Slice courgette, peppers and tomatoes.",
      "Layer in a baking dish and season.",
      "Pour over cream-egg mixture.",
      "Sprinkle with cheese and bake at 180°C for 35 minutes.",
    ],
  },
  {
    nameDe: "Rote-Bete-Eintopf",
    name: "Beetroot Stew",
    type: "main", category: "vegan", meat: "none",
    portionGrams: 380, basePrice: 1.10, sellPrice: 4.80, cookTimeMin: 45,
    kcalPerPortion: 280, protein: 8, fat: 6, carbs: 48,
    allergens: [],
    tags: ["vegan", "herbst", "gesund", "farbenfroh"],
    stepsDe: [
      "Rote Bete schälen und würfeln.",
      "Mit Zwiebeln, Kartoffeln und Kümmel anschwitzen.",
      "Mit Gemüsebrühe aufgießen und 30 Minuten köcheln.",
      "Mit Apfelessig, Salz und Dill abschmecken.",
      "Mit einem Klecks veganer Sahne servieren.",
    ],
    steps: [
      "Peel and dice beetroot.",
      "Sweat with onions, potatoes and caraway.",
      "Cover with vegetable stock and simmer 30 minutes.",
      "Season with apple vinegar, salt and dill.",
      "Serve with a dollop of vegan cream.",
    ],
  },
  {
    nameDe: "Quiche Lorraine",
    name: "Quiche Lorraine",
    type: "main", category: "meat", meat: "pork",
    portionGrams: 320, basePrice: 2.00, sellPrice: 6.80, cookTimeMin: 55,
    kcalPerPortion: 520, protein: 18, fat: 34, carbs: 32,
    allergens: ["gluten", "egg", "milk"],
    tags: ["frankreich", "buffet", "warm", "kalt"],
    stepsDe: [
      "Mürbteig ausrollen und eine Tarteform auslegen.",
      "Speck würfeln und anbraten, in der Form verteilen.",
      "Eier mit Sahne, Salz, Pfeffer und Muskat verquirlen.",
      "Guss über den Speck gießen, mit geriebenem Käse bestreuen.",
      "Bei 180°C 40 Minuten backen bis die Masse stockt.",
    ],
    steps: [
      "Roll out shortcrust and line a tart tin.",
      "Dice and fry bacon, distribute in tin.",
      "Whisk eggs with cream, salt, pepper and nutmeg.",
      "Pour over bacon, sprinkle with grated cheese.",
      "Bake at 180°C for 40 minutes until set.",
    ],
  },
  {
    nameDe: "Veganer Bolognese mit Linsenhack",
    name: "Vegan Bolognese with Lentil Mince",
    type: "main", category: "vegan", meat: "none",
    portionGrams: 400, basePrice: 1.20, sellPrice: 4.80, cookTimeMin: 35,
    kcalPerPortion: 420, protein: 20, fat: 6, carbs: 66,
    allergens: ["gluten"],
    tags: ["vegan", "nudeln", "kantine", "günstig"],
    stepsDe: [
      "Zwiebeln, Knoblauch und Sellerie anschwitzen.",
      "Rote Linsen zugeben und kurz anrösten.",
      "Passata und Gemüsebrühe zugeben, 25 Minuten köcheln.",
      "Mit Salz, Pfeffer, Oregano und Basilikum abschmecken.",
      "Mit Spaghetti und veganer Parmesan-Alternative servieren.",
    ],
    steps: [
      "Sweat onions, garlic and celery.",
      "Add red lentils and briefly fry.",
      "Add passata and vegetable stock, simmer 25 minutes.",
      "Season with salt, pepper, oregano and basil.",
      "Serve with spaghetti and vegan Parmesan alternative.",
    ],
  },

  // ── Beilagen ────────────────────────────────────────────────────────────────
  {
    nameDe: "Kartoffelpüree",
    name: "Mashed Potato",
    type: "side", category: "vegetarian", meat: "none",
    portionGrams: 200, basePrice: 0.40, sellPrice: 1.50, cookTimeMin: 25,
    kcalPerPortion: 180, protein: 4, fat: 7, carbs: 28,
    allergens: ["milk"],
    tags: ["beilage", "klassiker", "günstig"],
    stepsDe: [
      "Mehligkochende Kartoffeln schälen und kochen.",
      "Kartoffeln stampfen, warme Milch und Butter einarbeiten.",
      "Mit Salz, Pfeffer und Muskat abschmecken.",
    ],
    steps: [
      "Peel and boil floury potatoes.",
      "Mash potatoes, work in warm milk and butter.",
      "Season with salt, pepper and nutmeg.",
    ],
  },
  {
    nameDe: "Rotkohl mit Äpfeln",
    name: "Red Cabbage with Apples",
    type: "side", category: "vegan", meat: "none",
    portionGrams: 180, basePrice: 0.50, sellPrice: 1.80, cookTimeMin: 45,
    kcalPerPortion: 120, protein: 2, fat: 2, carbs: 24,
    allergens: [],
    tags: ["beilage", "klassiker", "herbst", "winter"],
    stepsDe: [
      "Rotkohl feinhobeln, Äpfel schälen und würfeln.",
      "Mit Zwiebeln in Öl anschmoren.",
      "Essig, Zucker und Lorbeer zugeben.",
      "40 Minuten bei kleiner Hitze schmoren. Abschmecken.",
    ],
    steps: [
      "Finely shred red cabbage, peel and dice apples.",
      "Braise with onions in oil.",
      "Add vinegar, sugar and bay leaf.",
      "Braise 40 minutes on low heat. Season.",
    ],
  },
  {
    nameDe: "Salzkartoffeln",
    name: "Boiled Potatoes",
    type: "side", category: "vegan", meat: "none",
    portionGrams: 200, basePrice: 0.25, sellPrice: 1.20, cookTimeMin: 25,
    kcalPerPortion: 150, protein: 4, fat: 0, carbs: 34,
    allergens: [],
    tags: ["beilage", "günstig", "klassiker"],
    stepsDe: [
      "Kartoffeln schälen und in Salzwasser 20 Minuten kochen.",
      "Abgießen, kurz ausdampfen lassen.",
      "Mit Butter und Petersilie servieren.",
    ],
    steps: [
      "Peel potatoes and boil in salted water 20 minutes.",
      "Drain, let steam briefly.",
      "Serve with butter and parsley.",
    ],
  },
  {
    nameDe: "Bratkartoffeln mit Speck und Zwiebeln",
    name: "Fried Potatoes with Bacon and Onions",
    type: "side", category: "meat", meat: "pork",
    portionGrams: 220, basePrice: 0.80, sellPrice: 2.80, cookTimeMin: 25,
    kcalPerPortion: 280, protein: 8, fat: 14, carbs: 30,
    allergens: [],
    tags: ["beilage", "klassiker", "deftig"],
    stepsDe: [
      "Vorgekochte Kartoffeln in Scheiben schneiden.",
      "Speck und Zwiebeln anbraten.",
      "Kartoffelscheiben zugeben und knusprig braten.",
      "Mit Salz, Pfeffer und Majoran würzen.",
    ],
    steps: [
      "Slice pre-cooked potatoes.",
      "Fry bacon and onions.",
      "Add potato slices and fry until crispy.",
      "Season with salt, pepper and marjoram.",
    ],
  },
  {
    nameDe: "Nudeln mit Butter",
    name: "Buttered Noodles",
    type: "side", category: "vegetarian", meat: "none",
    portionGrams: 200, basePrice: 0.30, sellPrice: 1.20, cookTimeMin: 12,
    kcalPerPortion: 280, protein: 8, fat: 8, carbs: 44,
    allergens: ["gluten", "milk", "egg"],
    tags: ["beilage", "kinder", "günstig", "schnell"],
    stepsDe: [
      "Nudeln in Salzwasser al dente kochen.",
      "Abgießen, mit Butter schwenken.",
      "Mit Salz und nach Wunsch Petersilie würzen.",
    ],
    steps: [
      "Cook pasta al dente in salted water.",
      "Drain, toss with butter.",
      "Season with salt and optionally parsley.",
    ],
  },
  {
    nameDe: "Gedünsteter Reis",
    name: "Steamed Rice",
    type: "side", category: "vegan", meat: "none",
    portionGrams: 180, basePrice: 0.25, sellPrice: 1.00, cookTimeMin: 18,
    kcalPerPortion: 200, protein: 4, fat: 0, carbs: 44,
    allergens: [],
    tags: ["beilage", "günstig", "schnell"],
    stepsDe: [
      "Reis waschen. Doppelte Menge Wasser zum Kochen bringen.",
      "Reis zugeben, Deckel drauf, 15 Minuten bei kleiner Hitze garen.",
      "5 Minuten quellen lassen, mit einer Gabel lockern.",
    ],
    steps: [
      "Rinse rice. Bring double amount of water to boil.",
      "Add rice, lid on, cook 15 minutes on low.",
      "Leave to steam 5 minutes, fluff with fork.",
    ],
  },
  {
    nameDe: "Sauerkraut",
    name: "Sauerkraut",
    type: "side", category: "vegan", meat: "none",
    portionGrams: 160, basePrice: 0.40, sellPrice: 1.50, cookTimeMin: 20,
    kcalPerPortion: 60, protein: 2, fat: 0, carbs: 10,
    allergens: [],
    tags: ["beilage", "klassiker", "deutsch", "probiotisch"],
    stepsDe: [
      "Sauerkraut mit Lorbeer, Wacholder und Kümmel in Topf geben.",
      "Mit etwas Weißwein und Brühe aufgießen.",
      "20 Minuten bei niedriger Hitze schmoren.",
      "Mit Salz und Pfeffer abschmecken.",
    ],
    steps: [
      "Place sauerkraut with bay leaf, juniper and caraway in pot.",
      "Add a little white wine and stock.",
      "Braise on low heat 20 minutes.",
      "Season with salt and pepper.",
    ],
  },

  // ── Salate ──────────────────────────────────────────────────────────────────
  {
    nameDe: "Blattsalat mit Essig-Öl-Dressing",
    name: "Mixed Leaf Salad with Vinaigrette",
    type: "salad", category: "vegan", meat: "none",
    portionGrams: 200, basePrice: 0.60, sellPrice: 2.50, cookTimeMin: 10,
    kcalPerPortion: 80, protein: 2, fat: 5, carbs: 6,
    allergens: ["mustard"],
    tags: ["salat", "leicht", "vegan", "beilage"],
    stepsDe: [
      "Salatblätter waschen und zupfen.",
      "Dressing aus Essig, Öl, Senf, Salz und Pfeffer anrühren.",
      "Salat mit Dressing vermengen.",
      "Mit Tomaten, Gurken und Radieschen garnieren.",
    ],
    steps: [
      "Wash and tear salad leaves.",
      "Mix dressing of vinegar, oil, mustard, salt and pepper.",
      "Toss salad with dressing.",
      "Garnish with tomatoes, cucumber and radishes.",
    ],
  },
  {
    nameDe: "Nudelsalat mit Würstchen",
    name: "Pasta Salad with Sausage",
    type: "salad", category: "meat", meat: "pork",
    portionGrams: 280, basePrice: 1.20, sellPrice: 4.50, cookTimeMin: 20,
    kcalPerPortion: 420, protein: 14, fat: 20, carbs: 46,
    allergens: ["gluten", "egg", "mustard"],
    tags: ["salat", "buffet", "kantine", "günstig"],
    stepsDe: [
      "Nudeln kochen und abkühlen.",
      "Würstchen in Scheiben schneiden.",
      "Paprika, Gurke und Maiskörner zugeben.",
      "Dressing aus Mayonnaise, Senf und Joghurt anrühren.",
      "Alles vermengen und abschmecken.",
    ],
    steps: [
      "Cook and cool pasta.",
      "Slice sausages.",
      "Add peppers, cucumber and sweetcorn.",
      "Mix dressing of mayonnaise, mustard and yoghurt.",
      "Combine everything and season.",
    ],
  },
  {
    nameDe: "Gurkensalat mit Dill",
    name: "Cucumber Salad with Dill",
    type: "salad", category: "vegan", meat: "none",
    portionGrams: 180, basePrice: 0.40, sellPrice: 1.80, cookTimeMin: 10,
    kcalPerPortion: 50, protein: 1, fat: 2, carbs: 6,
    allergens: [],
    tags: ["salat", "leicht", "beilage", "klassiker"],
    stepsDe: [
      "Gurken dünn hobeln, salzen und 10 Minuten Wasser ziehen lassen.",
      "Ausdrücken und mit Essig, Öl und Dill vermengen.",
      "Mit Pfeffer und Zucker abschmecken.",
    ],
    steps: [
      "Thinly slice cucumbers, salt and leave 10 minutes.",
      "Squeeze out and mix with vinegar, oil and dill.",
      "Season with pepper and sugar.",
    ],
  },
  {
    nameDe: "Kartoffelsalat Süddeutsch",
    name: "Bavarian Potato Salad",
    type: "salad", category: "vegan", meat: "none",
    portionGrams: 250, basePrice: 0.60, sellPrice: 2.80, cookTimeMin: 30,
    kcalPerPortion: 220, protein: 4, fat: 6, carbs: 36,
    allergens: ["mustard"],
    tags: ["salat", "bayerisch", "klassiker", "beilage"],
    stepsDe: [
      "Festkochende Kartoffeln in der Schale kochen, schälen und schneiden.",
      "Warme Brühe, Essig, Öl, Senf und Zwiebeln verrühren.",
      "Marinade über die Kartoffeln gießen, 30 Minuten ziehen lassen.",
      "Mit Salz, Pfeffer und Schnittlauch abschmecken.",
    ],
    steps: [
      "Boil waxy potatoes in their skins, peel and slice.",
      "Mix warm stock, vinegar, oil, mustard and onions.",
      "Pour marinade over potatoes, leave 30 minutes.",
      "Season with salt, pepper and chives.",
    ],
  },

  // ── Desserts ─────────────────────────────────────────────────────────────────
  {
    nameDe: "Rote Grütze mit Vanillesauce",
    name: "Red Berry Compote with Vanilla Sauce",
    type: "dessert", category: "vegetarian", meat: "none",
    portionGrams: 200, basePrice: 0.80, sellPrice: 3.20, cookTimeMin: 20,
    kcalPerPortion: 200, protein: 4, fat: 6, carbs: 34,
    allergens: ["milk"],
    tags: ["dessert", "norddeutsch", "sommer", "klassiker"],
    stepsDe: [
      "Gemischte Beeren mit Zucker und Wasser aufkochen.",
      "Stärke mit etwas Wasser anrühren und einrühren.",
      "Unter Rühren aufkochen bis die Masse eindickt.",
      "Abkühlen lassen.",
      "Mit fertig gekaufter oder selbst gemachter Vanillesauce servieren.",
    ],
    steps: [
      "Bring mixed berries to boil with sugar and water.",
      "Mix starch with a little water and stir in.",
      "Boil stirring until mixture thickens.",
      "Leave to cool.",
      "Serve with store-bought or homemade vanilla sauce.",
    ],
  },
  {
    nameDe: "Milchreis mit Zimt und Zucker",
    name: "Rice Pudding with Cinnamon and Sugar",
    type: "dessert", category: "vegetarian", meat: "none",
    portionGrams: 250, basePrice: 0.50, sellPrice: 2.50, cookTimeMin: 40,
    kcalPerPortion: 300, protein: 8, fat: 6, carbs: 54,
    allergens: ["milk"],
    tags: ["dessert", "klassiker", "kinder", "günstig"],
    stepsDe: [
      "Milchreis mit Milch, Zucker, Salz und Vanille aufkochen.",
      "40 Minuten bei kleiner Hitze quellen lassen, dabei rühren.",
      "In Schüsseln füllen.",
      "Mit Zimt und Zucker bestreuen.",
      "Warm oder kalt servieren.",
    ],
    steps: [
      "Bring pudding rice to boil with milk, sugar, salt and vanilla.",
      "Leave to swell 40 minutes on low heat, stirring.",
      "Fill into bowls.",
      "Sprinkle with cinnamon and sugar.",
      "Serve warm or cold.",
    ],
  },
  {
    nameDe: "Apfelstrudel mit Vanillesauce",
    name: "Apple Strudel with Vanilla Sauce",
    type: "dessert", category: "vegetarian", meat: "none",
    portionGrams: 180, basePrice: 1.00, sellPrice: 3.80, cookTimeMin: 50,
    kcalPerPortion: 380, protein: 6, fat: 12, carbs: 62,
    allergens: ["gluten", "egg", "milk", "nuts"],
    tags: ["dessert", "österreich", "klassiker", "herbst"],
    stepsDe: [
      "Strudelteig aus Mehl, Wasser, Öl und Ei kneten und ruhen lassen.",
      "Teig dünn ausziehen.",
      "Äpfel schälen, reiben, mit Zucker, Zimt und Rosinen mischen.",
      "Füllung auf Teig verteilen, einrollen.",
      "Mit Butter bestreichen und bei 180°C 35 Minuten backen.",
    ],
    steps: [
      "Knead strudel dough from flour, water, oil and egg, rest.",
      "Stretch dough thin.",
      "Peel, grate apples, mix with sugar, cinnamon and raisins.",
      "Spread filling on dough, roll up.",
      "Brush with butter and bake at 180°C for 35 minutes.",
    ],
  },
  {
    nameDe: "Grießbrei mit Beerenkompott",
    name: "Semolina Pudding with Berry Compote",
    type: "dessert", category: "vegetarian", meat: "none",
    portionGrams: 250, basePrice: 0.40, sellPrice: 2.20, cookTimeMin: 15,
    kcalPerPortion: 260, protein: 8, fat: 4, carbs: 48,
    allergens: ["milk", "gluten"],
    tags: ["dessert", "kinder", "klassiker", "günstig"],
    stepsDe: [
      "Milch mit Zucker und Vanille aufkochen.",
      "Grieß einrühren und unter Rühren 5 Minuten köcheln.",
      "In Schüsseln geben, abkühlen lassen.",
      "Beerenkompott aus gefrorenen Beeren mit Zucker kochen.",
      "Grießbrei mit Kompott servieren.",
    ],
    steps: [
      "Bring milk to boil with sugar and vanilla.",
      "Stir in semolina and simmer 5 minutes stirring.",
      "Pour into bowls, allow to cool.",
      "Cook berry compote from frozen berries with sugar.",
      "Serve semolina pudding with compote.",
    ],
  },
  {
    nameDe: "Schokoladenpudding",
    name: "Chocolate Pudding",
    type: "dessert", category: "vegetarian", meat: "none",
    portionGrams: 200, basePrice: 0.50, sellPrice: 2.00, cookTimeMin: 15,
    kcalPerPortion: 260, protein: 6, fat: 8, carbs: 42,
    allergens: ["milk", "gluten"],
    tags: ["dessert", "kinder", "schokolade", "schnell"],
    stepsDe: [
      "Milch mit Kakao und Zucker verrühren.",
      "Speisestärke in etwas Milch auflösen und einrühren.",
      "Unter ständigem Rühren aufkochen bis die Masse eindickt.",
      "In Schüsseln füllen und abkühlen lassen.",
    ],
    steps: [
      "Mix milk with cocoa and sugar.",
      "Dissolve cornstarch in a little milk and stir in.",
      "Bring to boil stirring constantly until thickened.",
      "Fill into bowls and leave to cool.",
    ],
  },
  {
    nameDe: "Obstsalat",
    name: "Fruit Salad",
    type: "dessert", category: "vegan", meat: "none",
    portionGrams: 200, basePrice: 0.70, sellPrice: 2.50, cookTimeMin: 10,
    kcalPerPortion: 100, protein: 1, fat: 0, carbs: 24,
    allergens: [],
    tags: ["dessert", "vegan", "leicht", "sommer"],
    stepsDe: [
      "Saisonales Obst schälen und würfeln.",
      "Mit Orangensaft und Minze vermengen.",
      "Nach Bedarf mit Honig oder Agavendicksaft süßen.",
    ],
    steps: [
      "Peel and dice seasonal fruit.",
      "Mix with orange juice and mint.",
      "Sweeten with honey or agave syrup as needed.",
    ],
  },

  // ── Kindermenü ──────────────────────────────────────────────────────────────
  {
    nameDe: "Spaghetti Bolognese",
    name: "Spaghetti Bolognese",
    type: "main", category: "meat", meat: "beef",
    portionGrams: 380, basePrice: 1.60, sellPrice: 5.50, cookTimeMin: 40,
    kcalPerPortion: 520, protein: 28, fat: 16, carbs: 62,
    allergens: ["gluten", "celery"],
    tags: ["kinder", "klassiker", "nudeln", "beliebt"],
    stepsDe: [
      "Hackfleisch scharf anbraten, Zwiebeln und Knoblauch zugeben.",
      "Tomatenmark kurz mitrösten, Passata und Brühe zugeben.",
      "30 Minuten köcheln, mit Salz, Pfeffer und Oregano abschmecken.",
      "Spaghetti al dente kochen.",
      "Nudeln mit Bolognese anrichten und mit Parmesan bestreuen.",
    ],
    steps: [
      "Sear mince well, add onions and garlic.",
      "Briefly fry tomato paste, add passata and stock.",
      "Simmer 30 minutes, season with salt, pepper and oregano.",
      "Cook spaghetti al dente.",
      "Plate noodles with bolognese and sprinkle with Parmesan.",
    ],
  },
  {
    nameDe: "Fischstäbchen mit Erbsen und Kartoffelpüree",
    name: "Fish Fingers with Peas and Mashed Potato",
    type: "main", category: "fish", meat: "none",
    portionGrams: 360, basePrice: 2.00, sellPrice: 5.80, cookTimeMin: 20,
    kcalPerPortion: 440, protein: 24, fat: 18, carbs: 44,
    allergens: ["fish", "gluten", "egg"],
    tags: ["kinder", "klassiker", "schnell", "beliebt"],
    stepsDe: [
      "Fischstäbchen nach Packungsanweisung im Ofen backen.",
      "Erbsen kurz in Salzwasser blanchieren.",
      "Kartoffelpüree zubereiten.",
      "Alles zusammen anrichten.",
    ],
    steps: [
      "Bake fish fingers in oven according to packet instructions.",
      "Briefly blanch peas in salted water.",
      "Prepare mashed potato.",
      "Plate everything together.",
    ],
  },
  {
    nameDe: "Pfannkuchen mit Apfelmus",
    name: "Pancakes with Apple Sauce",
    type: "main", category: "vegetarian", meat: "none",
    portionGrams: 300, basePrice: 0.80, sellPrice: 3.50, cookTimeMin: 20,
    kcalPerPortion: 400, protein: 10, fat: 14, carbs: 58,
    allergens: ["gluten", "egg", "milk"],
    tags: ["kinder", "klassiker", "schnell", "vegetarisch"],
    stepsDe: [
      "Teig aus Mehl, Eiern, Milch und Salz anrühren.",
      "Pfannkuchen in Butter goldbraun ausbacken.",
      "Apfelmus aus Äpfeln, Wasser und Zucker kochen.",
      "Pfannkuchen mit Apfelmus servieren.",
    ],
    steps: [
      "Mix batter from flour, eggs, milk and salt.",
      "Fry pancakes golden in butter.",
      "Cook apple sauce from apples, water and sugar.",
      "Serve pancakes with apple sauce.",
    ],
  },
];

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`Seeding recipe library — ${RECIPES.length} recipes…`);

  let inserted = 0;
  let skipped = 0;

  for (const recipe of RECIPES) {
    const id = randomUUID();
    // Upsert: conflict on name_de → update all fields to keep data fresh.
    const result = await db
      .insert(recipeLibrary)
      .values({ id, ...recipe })
      .onConflictDoUpdate({
        target: recipeLibrary.nameDe,
        set: {
          name: sql`excluded.name`,
          type: sql`excluded.type`,
          category: sql`excluded.category`,
          meat: sql`excluded.meat`,
          portionGrams: sql`excluded.portion_grams`,
          basePrice: sql`excluded.base_price`,
          sellPrice: sql`excluded.sell_price`,
          cookTimeMin: sql`excluded.cook_time_min`,
          kcalPerPortion: sql`excluded.kcal_per_portion`,
          protein: sql`excluded.protein`,
          fat: sql`excluded.fat`,
          carbs: sql`excluded.carbs`,
          allergens: sql`excluded.allergens`,
          stepsDe: sql`excluded.steps_de`,
          steps: sql`excluded.steps`,
          tags: sql`excluded.tags`,
        },
      })
      .returning({ id: recipeLibrary.id });

    if (result.length > 0) inserted++;
    else skipped++;
  }

  console.log(`Done. Upserted: ${inserted}, skipped: ${skipped}.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
